{% set name = "tensorflow-lattice" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/py2.py3/t/tensorflow-lattice/tensorflow_lattice-{{ version }}-py2.py3-none-any.whl
  sha256: e851bfd5c1735b16d9ef2effe0b251f90f61d6005e2e4246e46abcf65591c3df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation tensorflow_lattice-{{ version }}-py2.py3-none-any.whl
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - absl-py
    - numpy
    - pandas
    - six
    - scikit-learn
    - matplotlib-base
    - python-graphviz
    - tf-keras
  run_constrained:
    - tensorflow >=1.15

test:
  imports:
    - tensorflow_lattice
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/tensorflow-lattice/
  summary: A library that implements optionally monotonic lattice based models.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/tensorflow/lattice

extra:
  recipe-maintainers:
    - ehfd
    - maresb
