{% set name = "tensorflow-lattice" %}
{% set version = "2.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorflow_lattice-{{ version }}.tar.gz
  sha256: 207a56b9e085876952b654ef410d1b9c8223cd097fdb7cdaf00afcc0437a0f39
  patches:
    - setup.py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py
    - numpy
    - pandas
    - six
    - scikit-learn
    - matplotlib-base
    - python-graphviz
    # Dependencies are correctly pinned as of tf 2.6.0, so avoid previous versions:
    # What exactly did I mean with this comment?
    - tensorflow >=2.6

test:
  imports:
    - tensorflow_lattice
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tensorflow/lattice
  summary: A library that implements optionally monotonic lattice based models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
