{% set name = "tensorflow-lattice" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tensorflow_lattice-{{ version }}.tar.gz
  sha256: 0fb71bbc6fe79fd1bf78f4a0623aa9854bf4e6616ae8cd4a7263efe843158d12
  patches:
    - setup.py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - absl-py
    - numpy
    - pandas
    - six
    - scikit-learn
    - matplotlib-base
    - python-graphviz
    - tf-keras

test:
  imports:
    - tensorflow_lattice
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tensorflow/lattice
  summary: A library that implements optionally monotonic lattice based models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
