{% set name = "tensorflow-lattice" %}
{% set version = "2.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorflow_lattice-{{ version }}.tar.gz
  sha256: 08a2e5765859cfb8c2b75c47c385f6885ad1d8ea30d7f64647d636923ccf4a60

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --install-option="--release"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py
    - numpy
    - pandas
    - six
    - scikit-learn
    - matplotlib-base
    - python-graphviz
    - dm-sonnet
    - tensorflow >=2

test:
  imports:
    - tensorflow_lattice
    - tensorflow_lattice.layers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tensorflow/lattice
  summary: A library that implements optionally monotonic lattice based models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
