{% set name = "tensorflow-lattice" %}
{% set version = "2.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorflow_lattice-{{ version }}.tar.gz
  sha256: a02d9b28a657c0f862a21a60691b79374733d15eb58ab0a4acb14ba144244ab5

build:
  noarch: python
  # --install-option="--release" is required since setup.py defaults to nightly release
  script: {{ PYTHON }} -m pip install . -vv --install-option="--release"
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py
    - numpy
    - pandas
    - six
    - scikit-learn
    - matplotlib-base
    - python-graphviz
    # Depends on tensorflow:
    - dm-sonnet
    # Dependencies are correctly pinned as of tf 2.6.0, so avoid previous versions:
    # What exactly did I mean with this comment?
    - tensorflow >=2.6

test:
  imports:
    - tensorflow_lattice
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tensorflow/lattice
  summary: A library that implements optionally monotonic lattice based models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
